### PR TITLE
Added java matchingParens|mergeSort|Palindrome|reverseString

### PR DESCRIPTION
**Pull request by tatianajiselle**
Refactored Reverse String problem into its own directory. Added 4 java solutions.

### CODE REVIEW

**Comment by chatasweetie** [comment]
@tatianajiselle Please add links to your solutions to the mark down in each director.
example for merge sort: 
- [Tatiana's Solution - Java](https://github.com/chatasweetie/whiteboarding-and-coding-problems/blob/master/questions/merge_sort/solution/myMergeSort.java)

**Comment by tatianajiselle** [comment]
Is it alright to leave the solutions in the solutions folder as well, or would you prefer me to remove them after linking?

Thanks (:

**Comment by chatasweetie** [comment]
For reach problem, add your code to the problem's solution repo and add the link to the .md of that problem

ie. Factorial.md has the link to my python solution ( https://github.com/chatasweetie/whiteboarding-and-coding-problems/blob/master/questions/factorial/factorial.md)
& My actual factorial.py in the solution directory (https://github.com/chatasweetie/whiteboarding-and-coding-problems/blob/master/questions/factorial/solution/factorial.py)

**Comment by tatianajiselle** [comment]
got it (: thanks for clarifying!

**Pull request merged**
